<?php

namespace my\JobeetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryAffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryAffiliateRepository extends EntityRepository
{
}
